import type { Product } from "./types";

export const latestProducts: Product[] = [
  {
    id: "13",
    slug: "midea-inverter-quattro-microwave-oven-25l",
    title: "Midea Inverter Quattro Microwave Oven - 25L",
    price: 200000,
    category: "Home Appliances",
    categorySlug: "home-appliances",
    featured: false,
    daysAgo: 0,
    timeAgo: "16 hours ago",
    condition: "New",
    location: "Entebbe",
    description:
      "Midea Inverter Quattro Microwave Oven, 25 litres. Advanced inverter technology for even, precise cooking. Multiple power levels and pre-set cooking functions. Brand new in box.",
    seller: {
      name: "Tech Deals UG",
      phone: "256700123456",
      whatsapp: "256700123456",
      memberSince: "Jan 2026",
    },
    specs: [
      { label: "Capacity", value: "25 Litres" },
      { label: "Technology", value: "Inverter" },
      { label: "Power Levels", value: "Multiple" },
      { label: "Type", value: "Quattro" },
      { label: "Condition", value: "Brand New" },
    ],
  },
  {
    id: "14",
    slug: "iphone-8-white-64gb-excellent-condition",
    title: "iPhone 8 White 64GB - Excellent Condition",
    price: 250000,
    category: "Phones & Tablets",
    categorySlug: "phones-tablets",
    featured: false,
    daysAgo: 0,
    timeAgo: "19 hours ago",
    condition: "Like New",
    location: "Entebbe",
    description:
      "iPhone 8 in white, 64GB storage. Excellent condition with no cracks or scratches on screen. Battery health at 82%. Includes original charger and cable. Screen protector applied.",
    seller: {
      name: "Phones Hub UG",
      phone: "256701234567",
      whatsapp: "256701234567",
      memberSince: "Feb 2026",
    },
    specs: [
      { label: "Storage", value: "64GB" },
      { label: "Color", value: "White" },
      { label: "Battery Health", value: "82%" },
      { label: "Condition", value: "Excellent" },
      { label: "Accessories", value: "Charger + Cable" },
    ],
  },
  {
    id: "15",
    slug: "samsung-a05-67-hd-display",
    title: 'Samsung A05 | 6.7" HD+ Display | UGX 150,000',
    price: 150000,
    category: "Phones & Tablets",
    categorySlug: "phones-tablets",
    featured: false,
    daysAgo: 0,
    timeAgo: "19 hours ago",
    condition: "Used - Good",
    location: "Entebbe",
    description:
      'Samsung Galaxy A05. 6.7" HD+ display, 64GB storage, 4GB RAM, Android 13. Good battery life at 5000mAh. Minor wear on body, screen is perfect. Includes charger.',
    seller: {
      name: "Galaxy Shop",
      phone: "256702345678",
      whatsapp: "256702345678",
      memberSince: "Mar 2026",
    },
    specs: [
      { label: "Display", value: '6.7" HD+' },
      { label: "Storage", value: "64GB" },
      { label: "RAM", value: "4GB" },
      { label: "Battery", value: "5000mAh" },
      { label: "OS", value: "Android 13" },
    ],
  },
  {
    id: "16",
    slug: "chiq-50-inch-4k-smart-tv-google-tv",
    title: "CHiQ 50 inch 4K Smart TV | Google TV | UGX 900,000",
    price: 900000,
    category: "Electronics",
    categorySlug: "electronics",
    featured: false,
    daysAgo: 1,
    timeAgo: "1 day ago",
    condition: "New",
    location: "Entebbe",
    description:
      "CHiQ 50 inch 4K Ultra HD Smart TV with Google TV. Built-in Chromecast, Google Assistant, Netflix, YouTube pre-installed. 3 HDMI ports, 2 USB ports. Dolby Audio. Brand new with warranty.",
    seller: {
      name: "Electronics Hub",
      phone: "256703456789",
      whatsapp: "256703456789",
      memberSince: "Dec 2025",
    },
    specs: [
      { label: "Size", value: "50 inches" },
      { label: "Resolution", value: "4K UHD" },
      { label: "Smart TV", value: "Google TV" },
      { label: "HDMI", value: "3 Ports" },
      { label: "Audio", value: "Dolby Audio" },
    ],
  },
  {
    id: "17",
    slug: "wireless-earbuds-charging-case-black",
    title: "Wireless Earbuds with Charging Case - Black",
    price: 50000,
    category: "Electronics",
    categorySlug: "electronics",
    featured: false,
    daysAgo: 2,
    timeAgo: "2 days ago",
    condition: "New",
    location: "Entebbe",
    description:
      "True wireless earbuds with compact charging case. 6 hours battery life per charge, 18 hours total with case. Touch controls, built-in microphone, IPX5 sweat resistance. Black colour.",
    seller: {
      name: "Gadget Store",
      phone: "256704567890",
      whatsapp: "256704567890",
      memberSince: "Nov 2025",
    },
    specs: [
      { label: "Battery Life", value: "6 hrs (18 hrs w/ case)" },
      { label: "Water Resistance", value: "IPX5" },
      { label: "Controls", value: "Touch" },
      { label: "Microphone", value: "Built-in" },
      { label: "Color", value: "Black" },
    ],
  },
  {
    id: "18",
    slug: "tozo-a1-true-wireless-stereo-earbuds",
    title: "TOZO A1 True Wireless Stereo Earbuds - Brand New Sealed",
    price: 50000,
    category: "Electronics",
    categorySlug: "electronics",
    featured: false,
    daysAgo: 2,
    timeAgo: "2 days ago",
    condition: "New",
    location: "Entebbe",
    description:
      "TOZO A1 Mini Wireless Earbuds. Brand new in sealed box. IPX5 waterproof rating, 6-hour playtime with up to 24 hours using charging case. Deep bass Bluetooth 5.3 sound. Excellent deal.",
    seller: {
      name: "CRE8MARKET ENTEBBE",
      phone: "256751621506",
      whatsapp: "256751621506",
      verified: true,
      memberSince: "May 2025",
    },
    specs: [
      { label: "Battery Life", value: "6 hrs (24 hrs w/ case)" },
      { label: "Water Resistance", value: "IPX5" },
      { label: "Bluetooth", value: "5.3" },
      { label: "Playtime", value: "6 hours" },
      { label: "Condition", value: "Brand New Sealed" },
    ],
  },
  {
    id: "19",
    slug: "anker-soundcore-portable-bluetooth-speaker",
    title: "Anker SoundCore Portable Bluetooth Speaker - New",
    price: 150000,
    category: "Electronics",
    categorySlug: "electronics",
    featured: false,
    daysAgo: 2,
    timeAgo: "2 days ago",
    condition: "New",
    location: "Entebbe",
    description:
      "Anker SoundCore Bluetooth Speaker. 24-hour battery life, 360° full sound, IPX5 waterproof, built-in microphone. Brand new in original packaging. Connects to 2 phones simultaneously.",
    seller: {
      name: "CRE8MARKET ENTEBBE",
      phone: "256751621506",
      whatsapp: "256751621506",
      verified: true,
      memberSince: "May 2025",
    },
    specs: [
      { label: "Battery Life", value: "24 hours" },
      { label: "Sound", value: "360° Full" },
      { label: "Water Resistance", value: "IPX5" },
      { label: "Microphone", value: "Built-in" },
      { label: "Condition", value: "Brand New" },
    ],
  },
  {
    id: "20",
    slug: "oppo-a15-android-phone-32gb-3gb-ram",
    title: "OPPO A15 Android Phone - 32GB Storage, 3GB RAM",
    price: 100000,
    category: "Phones & Tablets",
    categorySlug: "phones-tablets",
    featured: false,
    daysAgo: 3,
    timeAgo: "3 days ago",
    condition: "Used - Good",
    location: "Entebbe",
    description:
      "OPPO A15 in good condition. 32GB storage, 3GB RAM, Android 10. Triple camera setup with 13MP main lens. 4230mAh battery. Fingerprint sensor on back.",
    seller: {
      name: "Phone City",
      phone: "256705678901",
      whatsapp: "256705678901",
      memberSince: "Oct 2025",
    },
    specs: [
      { label: "Storage", value: "32GB" },
      { label: "RAM", value: "3GB" },
      { label: "Camera", value: "13MP Triple" },
      { label: "Battery", value: "4230mAh" },
      { label: "OS", value: "Android 10" },
      { label: "Security", value: "Fingerprint" },
    ],
  },
  {
    id: "21",
    slug: "samsung-galaxy-a05s-black-128gb-4gb",
    title: "Samsung Galaxy A05s Black - Triple Camera 128GB 4GB",
    price: 150000,
    category: "Phones & Tablets",
    categorySlug: "phones-tablets",
    featured: false,
    daysAgo: 3,
    timeAgo: "3 days ago",
    condition: "Used - Good",
    location: "Entebbe",
    description:
      "Samsung Galaxy A05s in black. 128GB storage, 4GB RAM. 50MP triple camera system. 5000mAh long-life battery. Minor scratches on back cover, screen is perfect. Comes with charger.",
    seller: {
      name: "Samsung Hub",
      phone: "256706789012",
      whatsapp: "256706789012",
      memberSince: "Sep 2025",
    },
    specs: [
      { label: "Storage", value: "128GB" },
      { label: "RAM", value: "4GB" },
      { label: "Camera", value: "50MP Triple" },
      { label: "Battery", value: "5000mAh" },
      { label: "Color", value: "Black" },
    ],
  },
  {
    id: "22",
    slug: "hp-zbook-firefly",
    title: "HP ZBook Firefly",
    price: 2800000,
    category: "Computers & Laptops",
    categorySlug: "computers-laptops",
    featured: false,
    daysAgo: 4,
    timeAgo: "4 days ago",
    condition: "Used - Good",
    location: "Entebbe",
    description:
      'HP ZBook Firefly G8 mobile workstation. Intel Core i7 11th Gen, 16GB RAM, 512GB NVMe SSD. NVIDIA T500 4GB GPU. 14" FHD IPS display. ISV certified for professional creative work.',
    seller: {
      name: "Pro Laptops UG",
      phone: "256707890123",
      whatsapp: "256707890123",
      memberSince: "Aug 2025",
    },
    specs: [
      { label: "Processor", value: "Core i7 11th Gen" },
      { label: "RAM", value: "16GB" },
      { label: "Storage", value: "512GB NVMe" },
      { label: "GPU", value: "NVIDIA T500 4GB" },
      { label: "Display", value: '14" FHD IPS' },
      { label: "Certification", value: "ISV Certified" },
    ],
  },
  {
    id: "23",
    slug: "macbook-pro-2020",
    title: "MacBook Pro 2020",
    price: 2500000,
    category: "Computers & Laptops",
    categorySlug: "computers-laptops",
    featured: false,
    daysAgo: 4,
    timeAgo: "4 days ago",
    condition: "Like New",
    location: "Entebbe",
    description:
      "MacBook Pro 13-inch 2020, Apple M1 chip. 8GB unified memory, 256GB SSD. Space Gray. Battery cycle count under 100. Runs macOS Sonoma. Includes original MagSafe charger. Excellent condition.",
    seller: {
      name: "Apple Store UG",
      phone: "256708901234",
      whatsapp: "256708901234",
      memberSince: "Jul 2025",
    },
    specs: [
      { label: "Chip", value: "Apple M1" },
      { label: "RAM", value: "8GB Unified" },
      { label: "Storage", value: "256GB SSD" },
      { label: "Display", value: '13.3" Retina' },
      { label: "Color", value: "Space Gray" },
      { label: "OS", value: "macOS Sonoma" },
    ],
  },
  {
    id: "24",
    slug: "saachi-iron-box",
    title: "Saachi Iron Box",
    price: 45000,
    category: "Home Appliances",
    categorySlug: "home-appliances",
    featured: false,
    daysAgo: 2,
    timeAgo: "2 days ago",
    condition: "Used - Good",
    location: "Entebbe",
    description:
      "Saachi electric steam iron box. Variable temperature control, steam burst function, self-cleaning mode. Working perfectly. Good soleplate.",
    seller: {
      name: "Home Stuff",
      phone: "256709012345",
      whatsapp: "256709012345",
      memberSince: "Jun 2025",
    },
    specs: [
      { label: "Type", value: "Steam Iron" },
      { label: "Temperature", value: "Variable" },
      { label: "Steam Burst", value: "Yes" },
      { label: "Self-Cleaning", value: "Yes" },
      { label: "Brand", value: "Saachi" },
    ],
  },
  {
    id: "25",
    slug: "apple-airpods-pro-2",
    title: "Apple AirPods Pro 2",
    price: 80000,
    category: "Electronics",
    categorySlug: "electronics",
    featured: false,
    daysAgo: 4,
    timeAgo: "4 days ago",
    condition: "Used - Good",
    location: "Entebbe",
    description:
      "Apple AirPods Pro 2nd generation. Active Noise Cancellation, Transparency mode, Adaptive Audio. MagSafe charging case included. Battery health good. One ear tip size missing.",
    seller: {
      name: "iStore UG",
      phone: "256710123456",
      whatsapp: "256710123456",
      memberSince: "May 2025",
    },
    specs: [
      { label: "Noise Cancellation", value: "Active" },
      { label: "Transparency Mode", value: "Yes" },
      { label: "Adaptive Audio", value: "Yes" },
      { label: "Charging", value: "MagSafe" },
      { label: "Generation", value: "2nd" },
    ],
  },
  {
    id: "26",
    slug: "dell-latitude-7490",
    title: "Dell Latitude 7490",
    price: 1400000,
    category: "Computers & Laptops",
    categorySlug: "computers-laptops",
    featured: false,
    daysAgo: 4,
    timeAgo: "4 days ago",
    condition: "Used - Good",
    location: "Entebbe",
    description:
      'Dell Latitude 7490. Intel Core i7 8th Gen, 16GB DDR4, 512GB SSD. 14" FHD IPS display. LTE 4G modem built-in. Backlit keyboard, fingerprint reader. In great working condition.',
    seller: {
      name: "Dell Deals UG",
      phone: "256711234567",
      whatsapp: "256711234567",
      memberSince: "Apr 2025",
    },
    specs: [
      { label: "Processor", value: "Core i7 8th Gen" },
      { label: "RAM", value: "16GB DDR4" },
      { label: "Storage", value: "512GB SSD" },
      { label: "Display", value: '14" FHD IPS' },
      { label: "Connectivity", value: "LTE 4G" },
      { label: "Security", value: "Fingerprint" },
    ],
  },
  {
    id: "27",
    slug: "zte-mf935-4g-lte-mobile-wifi-router-mtn",
    title: "ZTE MF935 4G LTE Mobile WiFi Router - MTN",
    price: 50000,
    category: "Electronics",
    categorySlug: "electronics",
    featured: false,
    daysAgo: 2,
    timeAgo: "2 days ago",
    condition: "Used - Good",
    location: "Entebbe",
    description:
      "ZTE MF935 4G LTE Mobile WiFi Hotspot router, MTN Uganda locked. Connect up to 10 devices simultaneously. Compact pocket-size design. Includes original charger.",
    seller: {
      name: "Network Hub",
      phone: "256712345678",
      whatsapp: "256712345678",
      memberSince: "Mar 2025",
    },
    specs: [
      { label: "Network", value: "4G LTE" },
      { label: "Carrier", value: "MTN Locked" },
      { label: "Devices", value: "Up to 10" },
      { label: "Form Factor", value: "Pocket-size" },
      { label: "Condition", value: "Used - Good" },
    ],
  },
  {
    id: "28",
    slug: "digital-voice-recorder-hd-speakers-rec007",
    title: "Digital Voice Recorder with HD Speakers - REC007",
    price: 180000,
    category: "Electronics",
    categorySlug: "electronics",
    featured: false,
    daysAgo: 2,
    timeAgo: "2 days ago",
    condition: "New",
    location: "Entebbe",
    description:
      "REC007 Digital Voice Recorder with HD stereo speakers. 32GB built-in memory, up to 15 hours continuous recording. Noise reduction technology, MP3/WAV playback, USB transfer.",
    seller: {
      name: "Audio World UG",
      phone: "256713456789",
      whatsapp: "256713456789",
      memberSince: "Feb 2025",
    },
    specs: [
      { label: "Memory", value: "32GB Built-in" },
      { label: "Recording", value: "15 hours" },
      { label: "Playback", value: "MP3/WAV" },
      { label: "Speakers", value: "HD Stereo" },
      { label: "Noise Reduction", value: "Yes" },
      { label: "Interface", value: "USB" },
    ],
  },
];

export const allProducts: Product[] = [...latestProducts];

export function formatPrice(price: number): string {
  return `UGX ${price.toLocaleString("en-UG")}`;
}
